#!/bin/bash

if command -v module &>/dev/null; then
    echo "Module system detected. Loading Python..."
    module load Python
else
    echo ""
fi

python -m venv ./dnet_env
source ./dnet_env/bin/activate
pip install -r requirements.txt
deactivate