#!/bin/bash
# ========================================
# Don't change this part
# module load Python/3.11.3
# source cgraphs_env/bin/activate

LOGFILE=dist_output.log
echo "$(date '+%Y-%m-%d %H:%M:%S'): Starting distance calculation script..." >> "$LOGFILE"

# ========================================
# Under this line come the parameters to run the script with

#path to the psf file:
PSF_FILE='/Users/evabertalan/Documents/projects/JSR1_pka_proj/scripts/example_files/test_traj/read_protein_membrane_7_9cis_y126a_3_2x.psf'

#path to the dcd files. Files can be defined individually listed after each other. Or multiple files selected using the glob wildcards.
DCD_FILES=$(ls /Users/evabertalan/Documents/projects/JSR1_pka_proj/scripts/example_files/test_traj/9cis_y126a_last_20frames_pbc.dcd| grep -v 'PBC.dcd')


#path to the output folder, in this folder will be the calculation results saved
OUTPUTFOLDER='/Users/evabertalan/Documents/projects/JSR1_pka_proj/scripts/example_files/test_traj/dist_output'
CG_INPUT='/Users/evabertalan/Documents/projects/JSR1_pka_proj/scripts/example_files/test_traj/workfolder_old/3_water_wires/sim_atomwise/sim_atomwise_max_3_water_bridges_min_occupancy_0.1_water_wire_graph_info.txt'

mkdir -p $OUTPUTFOLDER
python3 -m dnet_dist "$PSF_FILE" $DCD_FILES "$CG_INPUT" --output_folder "$OUTPUTFOLDER" --start 2 --stop 15 --step 2 --max_water_distance 5 >> "$LOGFILE" 2>&1


# =====================================
# Don't change this part
echo "$(date '+%Y-%m-%d %H:%M:%S'): Finished distance calculation" >> "$LOGFILE"
# deactivate